Don't crash is env doesn't have XDG_CURRENT_DESKTOP
Traceback (most recent call last):
File "/usr/bin/mintupgrade", line 635, in
upgrader.upgrade()
File "/usr/bin/mintupgrade", line 433, in upgrade
current_desktop = os.environ["XDG_CURRENT_DESKTOP"].lower()
File "/usr/lib/python3.6/os.py", line 669, in __getitem__
raise KeyError(key) from None
KeyError: 'XDG_CURRENT_DESKTOP'